{% set version = "3.7.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-gsdesign
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/gsDesign_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gsDesign/gsDesign_{{ version }}.tar.gz
  sha256: e27b1cdd0d940432142c4b350f0a071c592e7d54de340af889fa6318c1be57fc

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-dplyr >=1.1.0
    - r-ggplot2 >=3.1.1
    - r-gt
    - r-magrittr
    - r-r2rtf
    - r-rlang
    - r-tibble
    - r-tidyr
    - r-xtable
  run:
    - r-base
    - r-dplyr >=1.1.0
    - r-ggplot2 >=3.1.1
    - r-gt
    - r-magrittr
    - r-r2rtf
    - r-rlang
    - r-tibble
    - r-tidyr
    - r-xtable

test:
  commands:
    - $R -e "library('gsDesign')"           # [not win]
    - "\"%R%\" -e \"library('gsDesign')\""  # [win]

about:
  home: https://cran.r-project.org/web/packages/gsDesign/index.html, https://github.com/keaven/gsDesign
  license: GPL-3.0-or-later
  summary: Derives group sequential designs and describes their properties.
  license_family: GPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: gsDesign
# Title: Group Sequential Design
# Description: Derives group sequential designs and describes their properties.
# Authors@R: person(given = "Keaven", family = "Anderson", email =
#           "keaven_anderson@merck.com", role = c('aut','cre'))
# Depends: R (>= 3.5.0), ggplot2 (>= 0.9.2)
# License: GPL (>= 3)
# Imports: stats,utils,
#         rlang,methods,xtable,graphics,plyr,tools,mvtnorm,dplyr,tibble
# Suggests: knitr, scales, rmarkdown, gt, testthat, covr, gridExtra,
#         tidyr
# VignetteBuilder: knitr
# Copyright: Copyright 2010, Merck Research Laboratories
# Date: 2020-05-06
# RoxygenNote: 7.1.0
# Encoding: UTF-8
# NeedsCompilation: yes
# Packaged: 2020-05-06 23:37:26 UTC; keaven
# Author: Keaven Anderson [aut, cre]
# Maintainer: Keaven Anderson <keaven_anderson@merck.com>
# Repository: CRAN
# Date/Publication: 2020-05-07 10:50:02 UTC
